baseURL = 'https://jbuget.fr'
languageCode = 'fr-fr'
title = 'Jérémy Buget'
theme = 'bloodywood'
enableRobotsTXT = true
enableGitInfo = true

defaultContentLanguage = "fr"
[language]
  lang = 'fr'
  languageName= 'Français'

[params]
  author = 'Jérémy Buget'
  description= 'Site personnel de Jérémy Buget. CTO. Manager. Coder. Streamer. Speaker. Writer. Papa pupuce.'

[markup]
  [markup.goldmark]
    [markup.goldmark.parser]
      autoHeadingID = true
      autoHeadingIDType = 'github'
      [markup.goldmark.parser.attribute]
        block = true
        title = true

  [markup.highlight]
    style = 'monokailight'
