baseURL = 'https://jbuget.fr'
languageCode = 'fr-fr'
title = 'Jérémy Buget'
theme = 'bloodywood'
enableRobotsTXT = true
enableGitInfo = true

defaultContentLanguage = "fr"
[language]
  lang = 'fr'
  languageName= 'Français'

[params]
  author = 'Jérémy Buget'
  description= 'Site personnel de Jérémy Buget. CTO. Manager. Coder. Streamer. Speaker. Writer. Papa pupuce.'

[markup]
  [markup.goldmark]
    [markup.goldmark.parser]
      autoHeadingID = true
      autoHeadingIDType = 'github'
      [markup.goldmark.parser.attribute]
        block = true
        title = true
    [markup.goldmark.renderer]
      unsafe = true

  [markup.highlight]
    style = 'monokailight'

# Algolia's integration
# See https://forestry.io/blog/search-with-algolia-in-hugo/
[outputFormats.Algolia]
  baseName = "algolia"
  isPlainText = true
  mediaType = "application/json"
  notAlternative = true
[params.algolia]
  vars = ["title", "summary", "date", "publishdate", "expirydate", "permalink"]
  params = ["categories", "tags"]
[outputs]
  home = ["HTML", "RSS", "Algolia"]
