baseURL = 'https://jbuget.fr'
languageCode = 'fr-fr'
title = 'Jérémy Buget'
theme = 'bloodywood'
defaultContentLanguage = "fr"
enableRobotsTXT = true
enableGitInfo = true

[params]
  author = 'Jérémy Buget'
  description= 'Site personnel de Jérémy Buget. CTO. Manager. Coder. Streamer. Speaker. Writer. Papa pupuce.'

[markup]
  [markup.goldmark]
    [markup.goldmark.parser]
      autoHeadingID = true
      autoHeadingIDType = 'github'
      [markup.goldmark.parser.attribute]
        block = true
        title = true
    [markup.goldmark.renderer]
      unsafe = true

  [markup.highlight]
    style = 'monokailight'

[services]
  [services.disqus]
    shortname = 'jbuget'
  [services.googleAnalytics]
    id = 'G-PBZJVEY0RX'


