baseURL = 'https://jbuget.fr'
languageCode = 'fr-fr'
title = 'Site Web personnel de Jérémy Buget'
theme = 'bloodywood'
enableRobotsTXT = true
enableGitInfo = true

[params]
  author = 'Jérémy Buget'

disqusShortname = 'jbuget'

[markup]
  [markup.goldmark]
    [markup.goldmark.parser]
      autoHeadingID = true
      autoHeadingIDType = 'github'
      [markup.goldmark.parser.attribute]
        block = true
        title = true
